export const ErrorCodes = {
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  AI_UNAVAILABLE: 'AI_UNAVAILABLE',
  CONTENT_POLICY_VIOLATION: 'CONTENT_POLICY_VIOLATION',
  UNAUTHORIZED: 'UNAUTHORIZED',
  NOT_FOUND: 'NOT_FOUND',
  STRIPE_WEBHOOK_DUPLICATE: 'STRIPE_WEBHOOK_DUPLICATE',
  EXPORT_IN_PROGRESS: 'EXPORT_IN_PROGRESS',
  DELETION_FAILED: 'DELETION_FAILED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
} as const

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes]
